name: jsaw_limited
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  responsive_builder: ^0.7.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^28.1.37
  url_strategy: ^0.2.0
  go_router: ^14.2.0
  http: ^1.2.1
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  hive: ^2.2.3
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
#  hive_generator: ^2.0.1
  localstorage: ^4.0.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  dio: ^5.5.0+1
  url_launcher: ^6.1.7
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  web: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: poppins
#      fonts:
#        - asset: assests/fonts/Poppins-Black.ttf
#        - asset: assests/fonts/Poppins-BlackItalic.ttf
#        - asset: assests/fonts/Poppins-Bold.ttf
#        - asset: assests/fonts/Poppins-BoldItalic.ttf
#        - asset: assests/fonts/Poppins-ExtraBold.ttf
#        - asset: assests/fonts/Poppins-ExtraBoldItalic.ttf
#        - asset: assests/fonts/Poppins-ExtraLight.ttf
#        - asset: assests/fonts/Poppins-ExtraLightItalic.ttf
#        - asset: assests/fonts/Poppins-Italic.ttf
#        - asset: assests/fonts/Poppins-Light.ttf
#        - asset: assests/fonts/Poppins-LightItalic.ttf
#        - asset: assests/fonts/Poppins-Medium.ttf
#        - asset: assests/fonts/Poppins-MediumItalic.ttf
#        - asset: assests/fonts/Poppins-Regular.ttf
#        - asset: assests/fonts/Poppins-SemiBold.ttf
#        - asset: assests/fonts/Poppins-SemiBolditalic.ttf
#        - asset: assests/fonts/Poppins-Thin.ttf

